osx_image: xcode9.2
language: objective-c
xcode_workspace: Iterable-iOS-SDK.xcworkspace
xcode_scheme: Iterable-iOS-SDKTests
xcode_sdk: iphonesimulator

before_install:
  - gem install xcpretty xcpretty-travis-formatter

script:
  - xcodebuild test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X' -workspace Iterable-iOS-SDK.xcworkspace -scheme Iterable-iOS-SDKTests CODE_SIGNING_REQUIRED=NO  | xcpretty -f `xcpretty-travis-formatter`
  - pod lib lint